spring:
  datasource:
    url: ${DBR_URL}
    username: ${DBR_USERNAME}
    password: ${DBR_PASSWORD}
  data:
    mongodb:
      host: ${MONGODB_URL}
      port: ${MONGODB_PORT}
      database: ${MONGODB_NAME}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTH}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMs: ${TOKEN_EXPIRATION}
  oauth2:
    google:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      scopes:
        - email
        - profile
  track:
    key: ${TRACK_KEY}
    time-in-microseconds: ${TRACK_TIME}
  node: ${NODE}
  activity:
    key: ${ACTIVITY_KEY}

redis:
  url: ${REDIS_URL}
  password: ${REDIS_PASSWORD}

server:
  port: ${PORT:8080}

amazon:
  endpointUrl: ${AMAZON_S3_ENDPOINT_URL}
  accessKey: ${AMAZON_S3_ACCESS_KEY}
  secretKey: ${AMAZON_S3_SECRET_KEY}
  bucketName: ${AMAZON_BUCKET_NAME}
