spring:
  datasource:
    url: ${DBR_URL}
    username: ${DBR_USERNAME}
    password: ${DBR_PASSWORD}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    default-property-inclusion: non_null

redis:
  url: ${REDIS_URL}
  password: ${REDIS_PASSWORD}

server:
  port: ${PORT}

statistic:
  teamIntervalInSeconds: ${TEAM_INTERVAL_IN_SECONDS}