# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Package file
      run: mkdir develop && cp target/*.jar develop
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: develop
    - name: Setup SSH
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1.0.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-host: 128.199.168.137
    - name: Copy Package to Server
      run: scp -r develop/*.jar udeploy@128.199.168.137:/server/usrun-statistic/dist
    - name: Deployment
      run: ssh udeploy@128.199.168.137 "cd /server/usrun-statistic/ && ./runserver restart"
